### PR TITLE
Auto-magically create release + assets

### PR DESCRIPTION
**Pull request by orangemug**
This PR automagically create the release and upload the assets to the release.

#### An example using my local repo
Create release

https://github.com/mikeebowen/OOXML-Validator/assets/235915/e836cb96-1e5b-452d-8ce7-8c2d0ef0e67d

Build passes and uploads assets 

Screenshot 2024-06-27 at 21 14 49

Assets added to the release

Screenshot 2024-06-27 at 21 14 24

### CODE REVIEW

**Comment by mikeebowen** [comment]
Thanks @orangemug, this will make the release process much easier

**Comment by orangemug** [comment]
@mikeebowen any chance of a new release soon(ish)?

I'm planning to add this into some CI processes next week

**Comment by mikeebowen** [comment]
NP! https://github.com/mikeebowen/OOXML-Validator/releases/tag/v2.1.5

The scripts worked great 👍 (updated to 2.1.5 to update the nuget packages)

**Comment by orangemug** [comment]
First off sorry to ask in this PR @mikeebowen, I couldn't find another way to message you.

I've found an odd font issue in msword, essentially is garbles fonts when embedding them under certain circumstances. Any idea where/how I'd go about reporting that to Microsoft without it just getting lost in a customer support issue tracker?

Any pointers in the right direction where to report would be very much appreciated.

**Comment by mikeebowen** [comment]
Hi @orangemug, unfortunately, I don't have any special channels to submit bugs to Word. If you have a support contract that would be the best way to communicate the bug. If you don't the main channels for doing so are:

- [The Feedback web portal](https://feedbackportal.microsoft.com/)
- In-product experiences
- Windows Feedback Hub
- [Microsoft Tech Community](https://techcommunity.microsoft.com/)
- Microsoft Store

I hope that helps

**Pull request merged**
